[package]
name = "nginx-cache-purge"
version = "0.4.4"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.89"
repository = "https://github.com/magiclen/nginx-cache-purge"
homepage = "https://magiclen.org/nginx-cache-purge"
keywords = ["nginx", "cache", "clear", "purge", "delete"]
categories = ["command-line-utilities"]
description = "An alternative way to do `proxy_cache_purge` or `fastcgi_cache_purge` for Nginx."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "Cargo.lock", "README.md", "LICENSE"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
clap = { version = "4", features = ["derive"] }
concat-with = "0.2"
terminal_size = "0.4"

anyhow = "1.0.12"

md-5 = "0.11"

tokio = { version = "1.44", features = ["rt-multi-thread", "net", "fs", "io-util"], optional = true }
hyper = { version = "1.1", optional = true }
hyper-util = { version = "0.1.3", features = ["server-auto"], optional = true }
tower = { version = "0.5.2", optional = true }
axum = { version = "0.8.4", optional = true }

tracing = { version = "0.1.37", optional = true }
enable-ansi-support = { version = "0.3", optional = true }
tracing-subscriber = { version = "0.3.10", features = ["env-filter"], optional = true }
tower-http = { version = "0.7", features = ["trace", "set-header"], optional = true }

[dev-dependencies]
tempfile = "3"

[features]
default = ["service"]
service = [
    "dep:tokio",
    "dep:hyper",
    "dep:hyper-util",
    "dep:tower",
    "dep:axum",
    "dep:tracing",
    "dep:enable-ansi-support",
    "dep:tracing-subscriber",
    "dep:tower-http"
]